### ISSUE TITLE
Failed to run the bot

### ISSUE THREAD

**Issue by chicoco16** [Gamerium/Dindo-Bot#28]
![image](https://user-images.githubusercontent.com/89115357/181123107-6824dded-95bc-4a69-a774-562f9dd58bcf.png)

Could you help me? thanks a lot geniuses

**Comment by AXeL-dev** [comment]
You are running the bot on a Wayland display server, you'll need to switch to Xorg.

![image](https://user-images.githubusercontent.com/30635693/181131078-b67e1e78-180c-4a3c-addb-ea5670bca65a.png)

**Comment by chicoco16** [comment]
What version of ubuntu do you have? It doesn't look the same to me
Thanks for your help.

**Comment by AXeL-dev** [comment]
Check this: https://github.com/Gamerium/Dindo-Bot/issues/17#issuecomment-614207564.

**Comment by chicoco16** [comment]
Thank you very much genius, I have been able to execute it, now I need to learn how to use it hehehe, I hope 5 dollars will help you (I'm from Argentina, I hope it's worth it, since it's too much money)

**Comment by AXeL-dev** [comment]
@chicoco16 Thanks man! i appreciate it! <3
